name: You are the Villain
description: Entry to the Ludum Dare 25
author: Dennis Kaselow <Dennis.Kaselow+ld25@gmail.com>
homepage: https://github.com/denniskaselow/ld25
dependencies:
  dartemis:
    git: git://github.com/denniskaselow/dartemis.git