name: ld25
description: Entry to the Ludum Dare 25 - You are the Villain
author: Dennis Kaselow <Dennis.Kaselow+ld25@gmail.com>
homepage: https://github.com/denniskaselow/ld25
dependencies:
  browser: any
  dartemis: any
  gamedev_helpers:
#    git: https://github.com/kayzgames/gamedev_helpers
    path: ../gamedev_helpers
  dart_to_js_script_rewriter: any
transformers:
- dart_to_js_script_rewriter